Repository SSAFY-10th-Seoul-13class-Algorithm/Baekjoon, pull requests merged in 2023-09, with the labels that each got.

#24 [6주차] 송윤재
  src/main/java/org/example/week_06/Main_1647_G4_도시분할계획_송윤재.java
  src/main/java/org/example/week_06/Main_3665_G1_최종순위_송윤재.java
Labels: 리뷰완료_김태수, 리뷰완료_김희연, 리뷰완료_강이규

#21 [6주차] 김태수
  src/main/java/org/example/week_06/Boj_1647_도시분할계획_김태수.java
  src/main/java/org/example/week_06/Boj_3665_최종순위_김태수.java
Labels: 리뷰완료_송윤재, 리뷰완료_김희연, 리뷰완료_강이규

#22 [6주차] 강이규
  src/main/java/org/example/week_06/Boj_1647_도시분할계획_강이규.java
  src/main/java/org/example/week_06/Boj_3665_최종순위_강이규.java
Labels: 리뷰완료_송윤재, 리뷰완료_김태수, 리뷰완료_김희연

#23 [6주차] 김희연
  src/main/java/org/example/week_06/Boj_1647_도시분할계획_김희연.java
  src/main/java/org/example/week_06/Boj_3665_최종순위_김희연.java
Labels: 리뷰완료_송윤재, 리뷰완료_김태수, 리뷰완료_강이규
